allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  core-js: true
  esbuild: true
  prisma: true
  react-tsparticles: true
  sharp: true
  tsparticles-engine: true
  unrs-resolver: true
